version: "2"

services:
  cms:
    build:
      context: ./
      dockerfile: Dockerfile-cms
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    command: "rails server -e production"

  nginx:
    image: registry.docker-cn.com/library/nginx
    volumes:
      - ./nginx/dist:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    command: "nginx -g 'daemon off;'"