web:
  image: nginx
  volumes:
    - ./dist:/usr/share/nginx/html
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./logs:/var/log/nginx
  ports:
    - "8001:80"
  command: "nginx -g 'daemon off;'"